"""empty message

Revision ID: 1c93e8706dcf
Revises: 4b3d3cfa017d
Create Date: 2015-02-11 21:44:59.548138

"""

# revision identifiers, used by Alembic.
revision = '1c93e8706dcf'
down_revision = '4b3d3cfa017d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
