"""empty message

Revision ID: 3b79d900cadc
Revises: None
Create Date: 2015-02-08 00:39:36.139174

"""

# revision identifiers, used by Alembic.
revision = '3b79d900cadc'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pay_num')
    op.drop_column('user', 'last_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_time', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('pay_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
