"""empty message

Revision ID: 222d18e4aaff
Revises: 3b79d900cadc
Create Date: 2015-02-08 00:44:06.188156

"""

# revision identifiers, used by Alembic.
revision = '222d18e4aaff'
down_revision = '3b79d900cadc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.String(length=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    ### end Alembic commands ###
