"""empty message

Revision ID: 4bb242bd2e52
Revises: 1c93e8706dcf
Create Date: 2015-02-23 22:55:58.313658

"""

# revision identifiers, used by Alembic.
revision = '4bb242bd2e52'
down_revision = '1c93e8706dcf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=1024), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=1024), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=1024), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('transaction')
    op.drop_table('item')
    op.alter_column(u'user', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(u'email', 'user', type_='unique')
    op.drop_index('email', table_name='user')
    op.drop_constraint(u'tel', 'user', type_='unique')
    op.drop_index('tel', table_name='user')
    op.drop_column(u'user', 'tel')
    op.drop_column(u'user', 'email')
    op.drop_column(u'user', 'sex')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('sex', mysql.VARCHAR(length=1), nullable=True))
    op.add_column(u'user', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.add_column(u'user', sa.Column('tel', mysql.VARCHAR(length=20), nullable=False))
    op.create_index('tel', 'user', ['tel'], unique=True)
    op.create_unique_constraint(u'tel', 'user', ['tel'])
    op.create_index('email', 'user', ['email'], unique=True)
    op.create_unique_constraint(u'email', 'user', ['email'])
    op.alter_column(u'user', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_table('item',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('summary', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('flag', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'user.id'], name=u'item_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('money', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], [u'item.id'], name=u'transaction_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'transaction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('author')
    op.drop_table('category')
    op.drop_table('book')
    ### end Alembic commands ###
